FIELDS = [
    "prefecture_code",
    "prefecture_name",
    "municipality_code",
    "municipality_name",
    "ward_name",

    "facility_name",
    "formal_name",
    "facility_category",
    "postal_code",
    "address",
    "latitude",
    "longitude",
    "homepage_url",

    "multipurpose_toilet",
    "wheelchair_toilet",
    "toilet_floor",
    "unisex_toilet_count",
    "male_toilet_count",
    "female_toilet_count",

    "washlet",
    "adult_bed",
    "ostomate",
    "voice_guidance",
    "baby_bed",
    "baby_chair",
    "child_toilet",
    "child_chair",
    "flush_type",
    "emergency_call_type",

    "male_urinal_with_rail",
    "male_western_toilet",
    "female_western_toilet",
    "male_baby_bed",
    "female_baby_bed",
    "male_baby_chair",
    "female_baby_chair",

    "entrance_step",
    "stroller_rental",
    "nursing_space",
    "diaper_changing_space",
    "kids_room",

    "source_dataset",
    "source_name",
    "source_url",
    "source_updated_at",
    "source_row",
    "attribute_note",
    "note",
]
